/**
 * Japanese Language Pack Extension
 * 日语语言包扩展 - 激活时注册日语翻译到应用
 * 翻译数据内联，避免 Blob URL 加载时 import 路径解析问题
 */

const translations = {
  common: {
    confirm: '確定', cancel: 'キャンセル', save: '保存', delete: '削除',
    loading: '読み込み中...', submit: '送信', login: 'ログイン', logout: 'ログアウト',
    current: '現在',
  },
  nav: {
    workspace: '創作ワークスペース', assets: 'アセット管理', projects: 'マイプロジェクト',
    sketch: 'スケッチ描画', settings: '設定', myAccount: 'マイアカウント',
    userCenter: 'ユーザーセンター', userMenu: 'ユーザーメニュー', my: 'マイページ',
    connected: '接続済み', disconnected: '未接続',
    pressForShortcuts: '? キーでショートカットを表示',
    studioTitle: '餃子アニメ AI Video Studio', studioName: '餃子アニメ',
    shortcutPrefix: 'Ctrl+', mainNav: 'メインナビゲーション', bottomNav: 'ボトムナビゲーション',
    showShortcuts: 'ショートカットヘルプを表示', templates: 'テンプレートライブラリ',
    marketplace: 'テンプレートマーケット', community: 'コミュニティ', pricing: '料金プラン',
  },
  settings: {
    title: '設定', subtitle: 'ワークスペースをカスタマイズ',
    appearance: {
      title: 'テーマを選択', dark: 'ダークモード',
      darkDesc: '暗い背景に優しい文字、夜間使用に最適で目の疲れを軽減',
      light: 'ライトモード', lightDesc: '明るい背景に濃い文字、日中の作業に最適で視覚的に清爽',
      highContrast: 'ハイコントラスト', highContrastDesc: '純黒背景に純白文字、最大限のコントラストで可読性向上',
      system: 'システムに従う', systemDesc: 'OSのダーク/ライトモード設定を自動で追従',
      switchedTo: '切り替え完了', fullscreen: 'フルスクリーン',
      fullscreenDesc: 'より没入感のあるフルスクリーンモードに切り替え',
      enterFullscreen: 'フルスクリーン開始', exitFullscreen: 'フルスクリーン終了',
      fullscreenEnabled: 'フルスクリーンモードに入りました', fullscreenDisabled: 'フルスクリーンモードを終了しました',
    },
    language: {
      title: '言語を選択', zhCN: '中文', zhCNDesc: '簡体字中国語をインターフェース言語として使用',
      enUS: 'English', enUSDesc: '英語をインターフェース言語として使用',
      jaJP: '日本語', jaJPDesc: '日本語をインターフェース言語として使用',
    },
    feedback: {
      title: 'フィードバック種別', detailLabel: '詳細説明',
      detailPlaceholder: '問題や提案を詳しく記述してください...',
      detailHint: '詳細な説明ほど、より良いサポートが可能です',
      contactLabel: '連絡先', contactOptional: '任意',
      contactPlaceholder: 'メールアドレスまたはその他の連絡先',
      submitBtn: 'フィードバックを送信', submitting: '送信中...',
      successMsg: 'フィードバックありがとうございます！',
      errorMsg: '送信に失敗しました。後でもう一度お試しください',
      networkError: 'ネットワークエラー。後でもう一度お試しください',
      types: { bug: 'バグ報告', feature: '機能要望', improvement: 'UX改善', other: 'その他のフィードバック' },
    },
    about: {
      title: 'について', appName: '餃子アニメ',
      appSubtitle: 'Qianxun (Hubei) Technology Co., Ltd.',
      version: 'バージョン', comingSoon: '近日公開',
      comicWorkbench: '漫画ワークベンチ', novelWorkbench: '小説ワークベンチ',
      shortVideoWorkbench: 'ショート動画ワークベンチ', musicWorkbench: '音楽ワークベンチ',
    },
    sections: {
      appearance: '外観', appearanceDesc: 'インターフェーステーマとスタイル',
      language: '言語', languageDesc: '表示言語を切り替え',
      ai_assistant: 'AI アシスタント', ai_assistantDesc: 'AI会話コンテキストと動作設定',
      storage: 'ストレージ', storageDesc: 'キャッシュとローカルデータ',
      security: 'セキュリティ', securityDesc: 'パスワードとアカウントセキュリティ',
      feedback: 'フィードバック', feedbackDesc: '改善にご協力ください',
      about: 'について', aboutDesc: 'バージョンと情報',
    },
    storage: {
      title: 'ローカルキャッシュ',
      description: '画像と動画は次回の高速読み込みのためにブラウザに自動キャッシュされます。',
      cacheSize: 'キャッシュサイズ', cacheCount: 'キャッシュ済み', cacheCountUnit: 'ファイル',
      clearCache: 'キャッシュをクリア', clearing: 'クリア中...',
      clearSuccess: 'キャッシュをクリアしました', clearFailed: 'キャッシュのクリアに失敗しました',
      notSupported: 'このブラウザはローカルキャッシュをサポートしていません', calculating: '計算中...',
    },
    security: {
      hintTitle: 'パスワードヒント',
      hintDesc: 'パスワードを思い出すためのヒントを設定してください。パスワード自体は入力しないでください。',
      hintPlaceholder: '例：よく使うパスワードの組み合わせ', save: '保存', saving: '保存中...',
      hintSaved: 'パスワードヒントを保存しました', hintSaveFailed: '保存に失敗しました',
      changePasswordTitle: 'パスワード変更',
      changePasswordDesc: '古いパスワードと新しいパスワードを入力してログイン情報を更新します。',
      oldPasswordPlaceholder: '古いパスワード', newPasswordPlaceholder: '新しいパスワード',
      confirmPasswordPlaceholder: '新しいパスワードを確認', changePasswordBtn: 'パスワードを変更',
      changing: '変更中...', passwordChanged: 'パスワードを変更しました',
      passwordChangeFailed: 'パスワードの変更に失敗しました',
      passwordMismatch: '新しいパスワードが一致しません',
      passwordTooShort: '新しいパスワードは6文字以上必要です',
      networkError: 'ネットワークエラー。後でもう一度お試しください',
    },
  },
  commandPalette: {
    placeholder: 'コマンドを検索...', noResults: '一致するコマンドが見つかりません',
    categories: { navigation: 'ナビゲーション', action: 'アクション', settings: '設定', recent: '最近使用' },
    commands: {
      showShortcuts: 'ショートカットヘルプを表示',
      themeDark: 'ダークモードに切り替え', themeLight: 'ライトモードに切り替え',
      themeHighContrast: 'ハイコントラストに切り替え', themeSystem: 'システムテーマに従う',
      langZh: '中文に切り替え', langEn: 'Switch to English', langJa: '日本語に切り替え',
    },
    hint: '↑↓で選択、Enterで実行、Escで閉じる',
  },
  onboarding: {
    skip: 'ツアーをスキップ', prev: '前へ', next: '次へ', finish: '始める',
    stepOf: 'ステップ', replayButton: 'オンボーディングツアーを再生',
    steps: {
      sidebar: { title: 'ナビゲーションサイドバー', description: 'これはメインナビゲーションエリアで、モジュール間を素早く切り替えられます。' },
      workspace: { title: '創作ワークスペース', description: 'ここから創作の旅を始めましょう。脚本を書き、絵コンテを生成します。' },
      assets: { title: 'アセット管理', description: 'キャラクター、シーン、小道具などの創作素材を管理します。' },
      shortcuts: { title: 'キーボードショートカット', description: '? キーですべてのショートカットを表示、Ctrl+Kでコマンドパレットを開きます。' },
      settings: { title: '個別設定', description: 'テーマ、言語設定などをカスタマイズして、快適な作業環境を整えましょう。' },
    },
  },
  dashboard: {
    title: 'ワークフロー概要', refresh: 'データを更新',
    stats: { projects: 'プロジェクト', scripts: '脚本', storyboards: '絵コンテ', aiCalls: 'AI 呼び出し' },
    recentProjects: '最近のプロジェクト',
    noProjects: 'まだプロジェクトがありません。作成を開始しましょう',
    updatedAgo: '前に更新', justNow: 'たった今', minutesAgo: '分前', hoursAgo: '時間前', daysAgo: '日前',
    loadError: 'データの読み込みに失敗しました',
  },
  auth: {
    title: '餃子アニメ', subtitle: 'AI 駆動の動画創作プラットフォーム',
    loginTab: 'ログイン', registerTab: '新規登録', username: 'ユーザー名', password: 'パスワード',
    adminAccessKey: '管理者アクセスキー', loginBtn: 'ログイン', registerBtn: '新規登録',
    fillAllFields: 'すべての項目を入力してください',
    adminKeyRequired: 'この管理者アカウントには管理者アクセスキーが必要です',
    loginFailed: 'ログインに失敗しました。後でもう一度お試しください',
    registerFailed: '登録に失敗しました。後でもう一度お試しください',
    checkingPermissions: 'アカウント権限を確認中...',
    adminAccountDetected: '管理者アカウントが検出されました。ログインには追加の管理者アクセスキーが必要です。',
    firstTime: '初めてですか？', hasAccount: 'すでにアカウントをお持ちですか？',
    goRegister: '今すぐ登録', goLogin: 'ログインに戻る',
    usernameMinLength: 'ユーザー名は3文字以上必要です', passwordMinLength: 'パスワードは6文字以上必要です',
    registrationClosed: '登録機能は現在停止中です。管理者にお問い合わせください',
    emailPlaceholder: 'メールアドレス', emailRequired: 'メールアドレスを入力してください',
    emailFormatRequired: 'メールアドレスでログインしてください',
    emailFormatInvalid: 'メールアドレスの形式が正しくありません。余分なスペースや全角記号がないか確認してください',
    cjkPunctuationWarning: '全角記号が検出されました。送信時に自動修正されます：',
  },
  projects: {
    title: 'マイプロジェクト', subtitle: '漫劇と脚本プロジェクトを管理',
    searchPlaceholder: 'プロジェクトを検索...', createBtn: '新規プロジェクト',
    editBtn: '編集', deleteBtn: '削除', openBtn: '開く',
    createTitle: '新規プロジェクト', editTitle: 'プロジェクトを編集',
    nameLabel: 'プロジェクト名', namePlaceholder: 'プロジェクト名を入力',
    descLabel: 'プロジェクト説明', descPlaceholder: 'プロジェクトの内容を説明...',
    coverLabel: 'カバー画像', coverPlaceholder: '画像URL（任意）',
    aiGenerateCover: 'AI でカバーを生成', aiGeneratingCover: 'カバー生成中...',
    aiCoverHint: 'まずプロジェクト名または説明を入力してください',
    aiCoverFailed: 'AI カバー生成に失敗しました', aiCoverSuccess: 'カバーを生成しました',
    statusLabel: 'プロジェクト状態', statusDraft: '下書き', statusInProgress: '進行中', statusCompleted: '完了',
    visualStyleLabel: 'ビジュアルスタイル', visualStyleHint: '（すべての画像/動画の画風を統一）',
    visualStylePromptPlaceholder: 'カスタム英語スタイルプロンプト（プリセットを上書き）',
    myStyles: 'マイスタイル', myStylesEmpty: 'まだカスタムスタイルがありません',
    myStylesAdd: '+ 新規スタイル', myStylesEdit: 'スタイルを編集',
    myStylesNameLabel: 'スタイル名', myStylesPromptLabel: 'スタイルプロンプト',
    myStylesCategoryLabel: 'スタイルカテゴリ',
    myStylesDeleteConfirm: 'スタイル「{name}」を削除しますか？',
    myStylesSaved: 'スタイルを保存しました', myStylesDeleted: 'スタイルを削除しました',
    myStylesNamePlaceholder: '例：クールなメカ',
    myStylesPromptPlaceholder: '例：メカスタイル, 金属質感, 未来科技',
    storyStyleLabel: '叙事スタイル', storyStylePlaceholder: '例：熱血少年漫画、サスペンス推理...',
    storyConstraintsLabel: '脚本制約', storyConstraintsPlaceholder: '例：魔法要素なし、現代都市...',
    narrativePerspectiveLabel: '撮影視点', narrativePerspectiveHint: '（脚本と絵コンテの叙事視点に影響）',
    perspectiveFirstPerson: '一人称', perspectiveFirstPersonDesc: '主観視点、没入感向上',
    perspectiveThirdPerson: '三人称', perspectiveThirdPersonDesc: '客観視点、自由なカメラ',
    outputLanguageLabel: 'AI 出力言語', outputLanguageHint: '（AI生成コンテンツの言語を制限）',
    outputLanguages: { en: 'English', zh: '中文', ja: '日本語', ko: '한국어', fr: 'Français', es: 'Español', de: 'Deutsch' },
    mangaLayoutLabel: '漫画レイアウト', mangaLayoutPage: 'ページ漫画', mangaLayoutStrip: 'ストリップ漫画', mangaLayoutFree: '自由レイアウト',
    mangaPanelStyleLabel: 'コマスタイル', mangaPanelStylePlaceholder: '例：整然コマ、不規則コマ、枠なし...',
    videoDurationLabel: '動画長', videoDuration15: '15秒', videoDuration30: '30秒', videoDuration60: '1分', videoDuration180: '3分',
    videoAspectLabel: '画面比率', videoAspect916: '9:16 縦型', videoAspect169: '16:9 横型', videoAspect11: '1:1 正方形',
    videoStyleLabel: '動画スタイル', videoStylePlaceholder: '例：Vlog、短編ドラマ、教育アニメ...',
    novelGenreLabel: '小説ジャンル', novelGenrePlaceholder: '例：ファンタジー、都市、SF、恋愛...',
    novelWritingStyleLabel: '文体', novelWritingStylePlaceholder: '例：ユーモラス、純文学、ウェブ小説...',
    novelChapterLengthLabel: '章の長さ', novelChapterLengthPlaceholder: '例：2000-3000字/章',
    novelTargetLabel: '対象読者', novelTargetPlaceholder: '例：男性向け、女性向け、全年齢...',
    aiSuggestBtn: 'AI スマート推奨設定', aiSuggesting: 'AI 分析中...',
    aiSuggestHint: 'まずプロジェクト名または説明を入力してください',
    presets: {
      animeJapanese: '日系アニメ', realisticFilm: '実写映画', render3D: '3Dレンダリング',
      pixar3D: 'ピクサー3D', disney3D: 'ディズニー3D', chinese3D: '中国3D', anime3D: '日系3D',
      watercolor: '水彩絵本', cyberpunk: 'サイバーパンク', americanComic: 'アメリカンコミック',
      pixelArt: 'ドット絵', chineseInk: '中国水墨画', shoujoManga: '少女漫画',
      fashionPhoto: 'ファッション写真', documentary: 'ドキュメンタリー', cinematicDrama: '映画感ドラマ', custom: 'カスタム',
    },
    styleCategoryLabel: 'コンテンツ種別', categoryLiveAction: '実写', categoryAnime: 'アニメ',
    bodyProportionLabel: '頭身比', bodyProportionHint: '（キャラクター描画の体型比率に影響）',
    proportionH2_5: '超SD', proportionH2_5Desc: '2.5頭身',
    proportionH3: '萌え系', proportionH3Desc: '3頭身',
    proportionH4: '少年/少女', proportionH4Desc: '4頭身',
    proportionH6: 'かわいい', proportionH6Desc: '6頭身',
    proportionH6_5: '日常', proportionH6_5Desc: '6.5頭身',
    proportionH7: 'ややスレンダー', proportionH7Desc: '7頭身',
    proportionH7_5: 'スレンダー', proportionH7_5Desc: '7.5頭身',
    proportionH8: 'スーパーモデル', proportionH8Desc: '8頭身',
    loadFailed: 'プロジェクトの読み込みに失敗しました',
    saveFailed: 'プロジェクトの保存に失敗しました。後でもう一度お試しください',
    deleteConfirmTitle: 'プロジェクトを削除',
    deleteConfirmMessage: 'このプロジェクトを削除してもよろしいですか？',
    deleteFailed: 'プロジェクトの削除に失敗しました。後でもう一度お試しください',
    aiRecommendFailed: 'AI推奨に失敗しました。後でもう一度お試しください',
    emptyTitle: 'プロジェクトがありません', emptyDesc: '「新規プロジェクト」をクリックして作成を開始',
    noDescription: '説明なし', updatedAt: '更新日',
  },
  userCenter: {
    title: 'ユーザーセンター', welcomeBack: 'お帰りなさい', joinedAt: '加入日',
    apiCalls: '回 API 呼び出し', accountBalance: 'アカウント残高', rechargeBtn: 'チャージ',
    totalSpent: '累計消費', totalTokens: '累計 Token', monthlyPoints: '今月の消費',
    monthlyPointsTooltip: '当月の累計ポイント消費', thisMonth: '今月', points: 'ポイント',
    works: '作品', images: '画像', videos: '動画', characters: 'キャラクター',
    charactersCreated: '作成キャラクター', projectCount: 'プロジェクト', scriptCount: '脚本',
    failedRequests: '失敗リクエスト', needsAttention: '要確認',
    billingTitle: '詳細請求', billingDesc: '各AIモデル呼び出しの状態、使用量、請求明細',
    billingEmpty: '請求記録がありません', colTime: '時間', colSource: 'ソース', colModel: 'モデル',
    colStatus: '状態', colBreakdown: '請求明細', colTotal: '合計',
    sourceWorkflow: 'ワークフロー', sourceRoute: '直接API', sourceAdminTool: '管理ツール', sourceUnknown: '不明',
    filterAllStatus: 'すべての状態', filterCharged: '課金済み', filterSkipped: 'スキップ', filterPending: '未決済',
    filterAllModels: 'すべてのモデル', filterTextModel: 'テキストモデル', filterImageModel: '画像モデル',
    filterVideoModel: '動画モデル', filterAudioModel: '音声モデル',
    filterAllSources: 'すべてのソース',
    usageInput: '入力', usageOutput: '出力', usageSeconds: '秒', usageItems: 'アイテム', usageTotalTokens: '総 Token',
    totalRecords: '合計', recordsUnit: '件の記録、', pageInfo: 'ページ {page} / {total}',
    prevPage: '前へ', nextPage: '次へ',
    fetchSummaryFailed: 'ユーザー概要の取得に失敗しました',
    fetchBillingFailed: '請求情報の取得に失敗しました',
  },
  assetsManager: {
    title: 'アセット管理', searchPlaceholder: 'アセットを検索...',
    aiGenerateCharacter: 'AI でキャラクターを生成', aiGenerateScript: 'AI で脚本を生成',
    newCharacter: '新規キャラクター', newStudio: '新規スタジオ', newProp: '新規小道具',
    newCostume: '新規衣装', newScript: '新規脚本', newEnvironment: '新規環境', newBuilding: '新規建物',
    tabs: {
      characters: 'キャラクター', props: '小道具', costumes: '衣装',
      environments: '環境', buildings: '建物', studios: 'スタジオ', scripts: '脚本',
    },
    sidebar: {
      projectList: 'プロジェクトリスト', allProjects: 'すべてのプロジェクト',
      unusedAssets: '未使用素材', noProjects: 'まだプロジェクトがありません',
      projectCount: '合計 {count} プロジェクト', expand: '展開', collapse: '折りたたみ',
      noAssets: 'アセットがありません', loading: '読み込み中...',
    },
    counts: {
      characters: '合計 {count} キャラクター', props: '合計 {count} 小道具',
      costumes: '合計 {count} 衣装', environments: '合計 {count} 環境',
      buildings: '合計 {count} 建物', studios: '合計 {count} スタジオ', scripts: '合計 {count} 脚本',
    },
    empty: {
      costumes: 'まだ衣装がありません。AI生成または手動で作成してください。',
      default: 'データがありません',
    },
    toasts: {
      selectProjectForAI: 'まず左側で対象プロジェクトを選択してください。AI生成キャラクターはプロジェクトの画風にバインドされます。',
      noProjectSelected: 'プロジェクトが選択されていません', missingCharacterId: 'characterId がありません',
      missingLocationId: 'locationId がありません',
    },
    groupFilter: { title: 'グループタグフィルタ', clear: 'フィルタをクリア' },
    heldProps: {
      title: 'キャラクター状態からの手持ち小道具',
      createAndGenerate: '小道具を作成してデザインを生成',
      selectImageModelFirst: 'まず画像生成モデルを選択してください',
      propCreated: '小道具「{name}」を作成しました',
      propImageGenStarted: '小道具デザイン生成を開始しました',
    },
    costume: {
      noImage: '画像なし', belongsTo: '所属キャラクター', generating: '生成中…',
      regenerate: '再生成', generateDesign: 'デザインを生成',
      descPlaceholder: 'クリックして説明を追加...', descUpdated: '衣装説明を更新しました',
    },
    studio: { elements: 'スタジオ要素', noBuildings: 'プロジェクトに建物がありません。まずアセットページで作成してください。' },
    script: { unNamed: '無名の脚本' },
    prop: {
      permanent: '常設小道具', held: '手持ち小道具', interactive: 'インタラクティブ小道具',
      statusCompleted: '完了', statusGenerating: '生成中', statusIdle: '待機中', statusFailed: '生成失敗',
    },
  },
  shortcuts: {
    title: 'キーボードショートカット', closeHint: 'Esc または背景をクリックして閉じる', close: '閉じる',
    scopes: {
      global: 'グローバルナビゲーション', storyboard: '絵コンテ操作', script: '脚本操作',
      assets: 'アセット管理', animatic: 'Animatic プレビュー', videoComposition: '動画合成',
    },
    descriptions: {
      navigateWorkspace: '創作ワークスペースへ', navigateAssets: 'アセット管理へ',
      navigateProjects: 'マイプロジェクトへ', navigateSketch: 'スケッチ描画へ', navigateSettings: '設定へ',
      showHelp: 'ショートカットヘルプを表示', openCommandPalette: 'コマンドパレットを開く',
      selectPrev: '前のシーンを選択', selectNext: '次のシーンを選択', deleteScene: '選択したシーンを削除',
      newScene: '新規シーンを追加', refreshList: 'シーンリストを更新', deselect: '選択を解除',
      moveUp: '選択したシーンを上へ移動', moveDown: '選択したシーンを下へ移動',
      lockScene: '選択したシーンをロック/解除', generateImage: '選択したシーンの画像を生成',
      generateVideo: '選択したシーンの動画を生成', duplicateScene: '選択したシーンを複製',
      selectAll: 'すべてのシーンを選択', validateStoryboard: '絵コンテを検証',
      playPause: '再生/一時停止', prevFrame: '前のシーン', nextFrame: '次のシーン',
      slowDown: '速度を下げる', speedUp: '速度を上げる', fullscreen: 'フルスクリーンプレビュー',
      muteToggle: 'ミュート/解除', closePreview: 'プレビューを閉じる',
      prevClip: '前のクリップ', nextClip: '次のクリップ', deleteClip: '選択したクリップを削除',
      exportVideo: '動画をエクスポート', clearTimeline: 'タイムラインをクリア',
      zoomIn: 'タイムラインを拡大', zoomOut: 'タイムラインを縮小', resetZoom: 'ズームをリセット',
      togglePanel: 'プロパティパネルを切り替え',
    },
  },
  errors: {
    unexpectedError: '予期しないエラーが発生しました',
    errorDescription: 'アプリケーションに問題が発生しました。ページを更新するか、ホームページに戻ってください。',
    retry: '再試行', backHome: 'ホームに戻る',
    networkOffline: 'ネットワークが切断されました。一部の機能が利用できない可能性があります',
    networkRestored: 'ネットワークが復旧しました',
    loadFailed: '読み込みに失敗しました', saveFailed: '保存に失敗しました',
    unknownError: '不明なエラー', pleaseRetry: '後でもう一度お試しください',
  },
  pricing: {
    title: 'あなたに合ったプランを選択', subtitle: '柔軟な料金プランで、あらゆる創作ニーズに対応',
    monthly: '月払い', yearly: '年払い', yearlyDiscount: '17% お得', perMonth: '/月', perYear: '/年',
    free: { name: '無料版', desc: '基本機能を体験', cta: '今すぐ始める' },
    basic: { name: 'ベーシック', desc: '個人クリエイターの入門に最適', cta: '今すぐ購読' },
    pro: { name: 'プロ', desc: '独立クリエイター向け', cta: '今すぐ購読' },
    premium: { name: 'プレミアム', desc: '小規模チームとスタジオ向け', cta: '今すぐ購読' },
    enterprise: { name: 'エンタープライズ', desc: '大規模チームと企業向け', cta: 'お問い合わせ' },
    features: {
      maxProjects: '最大プロジェクト数', maxApiCalls: '月間 API 呼び出し回数', maxTeamMembers: 'チームメンバー数',
      fullWorkflow: '完全ワークフロー', templateAccess: 'テンプレートライブラリアクセス',
      communityRanking: 'コミュニティランキング', teamCollaboration: 'チーム協働',
      versionControl: 'バージョン管理', prioritySupport: '優先サポート',
      privateDeploy: 'プライベートデプロイ', customIntegration: 'カスタム統合',
      industryData: '業界データ分析', dedicatedManager: '専任マネージャー',
    },
    currentPlan: '現在のプラン', upgradePlan: 'プランをアップグレード', popular: '最も人気', compareFeatures: '機能を比較',
  },
  subscription: {
    title: 'マイサブスクリプション', currentPlan: '現在のプラン', planExpiry: '有効期限',
    apiUsage: 'ポイント使用量', apiUsageOf: '{used} / {total} 使用中',
    projectUsage: 'プロジェクト使用量', upgrade: 'アップグレード',
    cancel: 'サブスクリプションをキャンセル', cancelConfirm: 'サブスクリプションをキャンセルしますか？',
    renewsOn: '更新日', trialEnds: '試用終了', noPlan: '未購読', freeTrial: '無料試用中',
    status: { active: '有効', expired: '期限切れ', cancelled: 'キャンセル済み', trial: '試用中' },
  },
  templates: {
    title: 'テンプレートライブラリ', subtitle: 'テンプレートから始めて、より速く創作',
    search: 'テンプレートを検索...',
    categories: { all: 'すべて', script: '脚本', storyboard: '絵コンテ', character: 'キャラクター', workflow: 'ワークフロー' },
    sortBy: { popular: '最も人気', newest: '最新', mostUsed: '最も使用多' },
    useTemplate: 'テンプレートを使用', preview: 'プレビュー', usedCount: '{count} 回使用',
    official: '公式', createdBy: '作成者', empty: 'テンプレートがありません',
    createFromProject: 'プロジェクトから作成',
  },
  marketplace: {
    title: 'テンプレートマーケット', subtitle: '優れたプロンプトレシピを発見して、創作のインスピレーションを解き放つ',
    sortHot: '人気', sortNewest: '最新', sortFree: '無料', sortPaid: '有料',
    recipeTypeCharacter: 'キャラクター', recipeTypeScene: 'シーン', recipeTypeScript: '脚本',
    freeTag: '無料', empty: 'まだテンプレートがありません', emptyHint: 'アップロードして試してみましょう',
    searchPlaceholder: 'プロンプトレシピを検索...', createRecipe: 'レシピを公開', myShop: 'マイショップ',
    noRecipeYet: 'まだ作品をアップロードしていません',
    uploadFirstHint: '最初の作品をアップロードして、プロンプトレシピを共有しましょう',
    uploadFirstBtn: '最初のレシピを公開', purchaseSuccess: '購入成功', freeGetSuccess: '無料取得成功',
    likeSuccess: 'いいねしました', unlikeSuccess: 'いいねを解除しました',
    followSuccess: 'フォローしました', unfollowSuccess: 'フォローを解除しました',
    commentSuccess: 'コメントを投稿しました', listSuccess: '出品成功', delistSuccess: '取り下げ成功',
    deleteSuccess: '削除成功', balanceInsufficient: 'ポイント残高が不足しています',
    recipePreview: 'レシピプレビュー', recipeUnlocked: 'レシピを解除しました',
    purchaseToUnlock: '購入後に完全なコンテンツを解除', sellerManagement: '販売者管理',
    myTemplates: 'マイレシピ', myPurchases: '購入履歴', earnings: '収入統計',
    createNew: '新規レシピを公開', price: '価格', free: '無料', listed: '出品中',
    delisted: '取り下げ済み', draft: '下書き', list: '出品', delist: '取り下げ',
    totalEarnings: '累計収入', totalSales: '総売上', recentSales: '最近の取引',
    recipeRanking: 'レシピランキング', platformFee: 'プラットフォーム手数料 (30%)',
    yourRevenue: 'あなたの収入', shopDescription: 'ショップ説明',
  },
  community: {
    title: 'クリエイターコミュニティ', subtitle: '素晴らしい作品を発見し、クリエイターとつながる',
    showcases: '作品広場', leaderboard: 'ランキング',
    filter: { hot: '最も人気', newest: '最新', featured: 'おすすめ' },
    showcase: {
      publish: '作品を公開', edit: '編集', views: '閲覧', likes: 'いいね',
      like: 'いいね', liked: 'いいね済み', featured: 'おすすめ', draft: '下書き',
      published: '公開済み', hidden: '非公開', empty: 'まだ作品がありません',
    },
    creator: {
      profile: 'クリエイタープロフィール', works: '作品', totalViews: '総閲覧数', totalLikes: '総いいね数',
      editProfile: 'プロフィールを編集', displayName: '表示名', bio: '自己紹介',
      socialLinks: 'ソーシャルリンク',
      badges: { newcomer: '新人', creator: 'クリエイター', pro: 'プロ', master: 'マスター' },
    },
    leaderboardTab: { weekly: '週間', monthly: '月間', allTime: '総合', rank: '順位', worksCount: '作品数', totalViews: '閲覧数' },
  },
  quickStart: {
    title: 'クイックスタート', subtitle: '数分で創作を開始',
    step1Title: '創作種別を選択', step1Desc: '作成したいコンテンツの種別を選択',
    types: { comic_drama: '漫劇', short_video: 'ショート動画', manga: '漫画', novel: '小説' },
    step2Title: 'テンプレートを選択', step2Desc: 'テンプレートから、またはゼロから開始',
    fromScratch: 'ゼロから開始',
    step3Title: 'プロジェクト情報', step3Desc: '作品に名前をつける',
    projectName: 'プロジェクト名', projectDesc: 'プロジェクト説明',
    step4Title: '創作を開始！', step4Desc: 'すべての準備が整いました',
    createProject: 'プロジェクトを作成', quickCreate: 'クイック作成',
  },
  workbench: {
    comicDrama: '漫劇ワークベンチ', comic_drama: '漫劇ワークベンチ',
    manga: '漫画ワークベンチ', shortVideo: 'ショート動画ワークベンチ',
    short_video: 'ショート動画ワークベンチ', novel: '小説ワークベンチ',
    comicDramaTabs: { script: '脚本生成', storyboard: '絵コンテ設計', composition: '動画合成' },
    comic_dramaTabs: { script: '脚本生成', storyboard: '絵コンテ設計', composition: '動画合成' },
    mangaTabs: { script: '脚本/シナリオ', layout: 'ページレイアウト', drawing: '描画ツール' },
    shortVideoTabs: { script: '動画脚本', timeline: 'タイムライン編集', effects: 'エフェクト追加' },
    short_videoTabs: { script: '動画脚本', timeline: 'タイムライン編集', effects: 'エフェクト追加' },
    novelTabs: { outline: 'アウトライン計画', chapters: '章管理', editor: 'テキストエディタ' },
    selectProject: 'まずプロジェクトを選択してください', noProject: 'プロジェクトが選択されていません',
    loading: '読み込み中...',
    mangaDetails: {
      pageLayout: {
        title: 'ページレイアウト', addPage: 'ページを追加', pageNumber: '第 {n} ページ',
        panels: 'コマ', addPanel: 'コマを追加', deletePanel: 'コマを削除',
        panelContent: 'コマ内容', panelDialogue: 'セリフ', panelDescription: '説明',
        generateImage: '画像を生成', layoutGrid: 'グリッドレイアウト', layoutFreeform: '自由レイアウト',
      },
      drawingTools: {
        title: '描画ツール', brush: 'ブラシ', eraser: '消しゴム', fill: '塗りつぶし', select: '選択',
        brushSize: 'ブラシサイズ', brushOpacity: '不透明度', layers: 'レイヤー',
        addLayer: 'レイヤーを追加', deleteLayer: 'レイヤーを削除', mergeLayer: 'レイヤーを統合',
        aiAssist: 'AI 補助', aiRefine: 'AI 最適化', aiColorize: 'AI カラー化',
      },
    },
    shortVideoDetails: {
      effects: {
        title: 'エフェクトエディタ', transitions: 'トランジション', filters: 'フィルター',
        stickers: 'ステッカー', text: 'テキスト', audio: 'オーディオ',
        addTransition: 'トランジションを追加', addFilter: 'フィルターを追加',
        addSticker: 'ステッカーを追加', addText: 'テキストを追加',
        transitionTypes: { fade: 'フェード', slide: 'スライド', zoom: 'ズーム', wipe: 'ワイプ', dissolve: 'ディゾルブ' },
      },
    },
    novelDetails: {
      outline: {
        title: 'アウトライン計画', addNode: 'ノードを追加', deleteNode: 'ノードを削除',
        editNode: 'ノードを編集', rootNode: 'ルートノード', plotPoint: 'プロットポイント',
        character: 'キャラクター', setting: '設定',
        aiGenerate: 'AI でアウトラインを生成', aiExpand: 'AI で拡張',
        expandAll: 'すべて展開', collapseAll: 'すべて折りたたみ',
      },
      chapters: {
        title: '章管理', addChapter: '章を追加', deleteChapter: '章を削除', editChapter: '章を編集',
        chapterTitle: '章タイトル', wordCount: '文字数', status: '状態',
        statusDraft: '下書き', statusWriting: '執筆中', statusComplete: '完了',
        reorder: '並べ替え', totalWords: '総文字数',
      },
      editor: {
        title: 'テキストエディタ', placeholder: '書き始め...', autoSave: '自動保存',
        saved: '保存済み', saving: '保存中...', wordCount: '文字数', charCount: '文字数（文字単位）',
        aiAssist: 'AI 執筆補助', aiContinue: 'AI 続き', aiRewrite: 'AI 書き換え', aiPolish: 'AI ブラッシュアップ',
        formatting: { bold: '太字', italic: '斜体', underline: '下線', heading: '見出し', quote: '引用', list: 'リスト' },
      },
    },
  },
  landing: {
    hero: {
      title: '物語を持つすべての人が、百万再生の AI 漫劇を作れる',
      subtitle: 'スケッチ駆動 AI 生成、100% 絵コンテと叙事リズムをロック',
      cta: '無料で創作を開始', ctaSecondary: '料金プランを見る',
    },
    features: {
      title: '強力な創作ツールチェーン', subtitle: '脚本から完成動画まで、ワンストップ AI 漫劇創作',
      scriptStudio: { title: 'スマート脚本スタジオ', desc: 'AI 補助脚本創作、スマート絵コンテ提案' },
      storyboard: { title: '絵コンテ管理システム', desc: 'スケッチ駆動 AI 絵コンテ生成、精密な画面コントロール' },
      sketchStudio: { title: 'スケッチスタジオ', desc: '棒人間/絵コンテスケッチ/精密線画、マルチモード創作' },
      assetManager: { title: 'アセット管理', desc: 'キャラクター三面図、シーン、小道具を一元管理' },
      videoComposer: { title: '動画コンポーザー', desc: 'タイムライン編集、音轨、字幕でプロ級出力' },
      aiEngine: { title: 'AI エンジン', desc: 'マルチモデル統合、ワークフロー自動化で効率的創作' },
    },
    workflow: {
      title: '3ステップで創作完了',
      step1: { title: 'スケッチを描く', desc: '棒人間でインスピレーションを描き出す' },
      step2: { title: 'AI 生成', desc: 'ワンクリックで美しい絵コンテを生成' },
      step3: { title: '完成動画をエクスポート', desc: '自動合成で高品質動画を出力' },
    },
    testimonials: { title: 'クリエイターの声' },
    cta: {
      title: '創作を始める準備はできましたか？',
      subtitle: '数千人のクリエイターに加わり、AI 漫劇の旅を始めましょう',
      button: '今すぐ無料で試す',
    },
    footer: {
      copyright: '© 2026 餃子アニメ. All rights reserved.',
      links: { about: '私たちについて', pricing: '料金プラン', community: 'コミュニティ', terms: '利用規約', privacy: 'プライバシーポリシー' },
    },
  },
  teams: {
    title: 'マイチーム', subtitle: 'チーム協働の管理と参加',
    create: 'チームを作成', edit: 'チームを編集', delete: 'チームを削除',
    leave: 'チームを退出', settings: 'チーム設定', members: 'メンバー', projects: 'プロジェクト',
    name: 'チーム名', description: 'チーム説明',
    noTeams: 'まだチームに参加していません',
    noTeamsHint: 'チームを作成するか、招待リンクから参加',
    noProjects: 'このチームにプロジェクトがありません',
    noProjectsHint: 'プロジェクト作成時にこのチームに割り当て可能',
    inviteLink: '招待リンク', inviteLinkDesc: 'このリンクを共有して他の人を招待',
    inviteCopied: '招待リンクをコピーしました',
    deleteConfirm: 'チーム「{name}」を削除しますか？この操作は元に戻せません。',
    leaveConfirm: 'チーム「{name}」を退出しますか？',
    roles: { owner: 'オーナー', admin: '管理者', editor: '編集者', viewer: '閲覧者' },
    roleDescriptions: {
      owner: '完全なコントロール権限', admin: 'コンテンツ編集とメンバー管理が可能',
      editor: 'コンテンツ編集可能、メンバー管理不可', viewer: 'コンテンツ閲覧のみ、編集不可',
    },
    addMember: 'メンバーを追加', removeMember: 'メンバーを削除', changeRole: 'ロールを変更',
    searchUser: 'ユーザー名を検索...',
    memberAdded: 'メンバーを追加しました', memberRemoved: 'メンバーを削除しました', roleUpdated: 'ロールを更新しました',
  },
  collaboration: {
    title: '協働者', addCollaborator: '協働者を追加', removeCollaborator: '協働者を削除',
    noCollaborators: '他の協働者はいません',
    noCollaboratorsHint: '上のボタンをクリックして協働者を追加',
    projectOwner: 'プロジェクト作成者',
    teamProject: 'このプロジェクトはチームに所属しており、チームメンバーは自動的にアクセス可能',
    inviteLink: '招待リンク', inviteLinkDesc: 'このリンクを共有して他の人をプロジェクトに招待',
    collaboratorAdded: '協働者を追加しました', collaboratorRemoved: '協働者を削除しました',
  },
  extensions: {
    title: '拡張機能マーケット', subtitle: '拡張機能を閲覧・管理',
    marketplace: 'マーケット', installed: 'インストール済み',
    searchPlaceholder: '拡張機能を検索...', category: 'カテゴリ', all: 'すべて',
    sort: '並び替え', sortDownload: 'ダウンロード多い順', sortNewest: '最新順', sortRating: '評価高い順', sortName: '名前順',
    noExtensions: '拡張機能が見つかりません', tryOtherSearch: '別のキーワードやカテゴリを試してください',
    loadMore: 'もっと読み込む', installedBadge: 'インストール済み', install: 'インストール', installing: 'インストール中...',
    uninstall: 'アンインストール', enable: '有効化', disable: '無効化', enabled: '有効', disabled: '無効',
    noInstalled: 'インストール済みの拡張機能がありません', browseMarketplace: 'マーケットを閲覧',
    noInstalledAny: 'まだ拡張機能がインストールされていません', goBrowse: '拡張機能マーケットへ',
    installedManage: 'インストール済み拡張機能の管理',
    unknownAuthor: '不明な作者', noDescription: '説明なし', noDocs: 'ドキュメントなし',
    downloads: 'ダウンロード', updateAvailable: '更新あり', updateTo: '更新先',
    categories: { productivity: '生産性ツール', theme: 'テーマ外観', tool: 'ユーティリティ', integration: '統合', other: 'その他' },
  },
  invite: {
    title: '{type}に参加', joinTeam: 'チームに参加', joinProject: 'プロジェクトに参加',
    invitedBy: '{name}があなたを招待しました', role: 'ロール', expiresAt: '招待の有効期限',
    accept: '招待を受け入れる', loginRequired: '招待を受け入れるにはログインが必要です',
    loginOrRegister: 'ログイン / 新規登録', success: '参加しました！',
    invalid: '招待が存在しないか、期限切れです', expired: '招待の期限が切れました',
    usedUp: '招待の使用上限に達しました', alreadyMember: 'すでにこの{type}のメンバーです',
  },
};

export function activate(api) {
  api.language.registerTranslations('ja-JP', '日本語', translations);
}

export function deactivate(api) {
  api.language.unregisterTranslations('ja-JP');
}
